#the snake for sum1d
rule sum_signal1d:
    input: 
        script="sum_signal1d"

    output:
        "rootfile/run{runnumber}_{clsize}_sum1d.root"  
    log:
        "logs/run{runnumber}_{clsize}.log"
    benchmark:
        "benchmarks/run{runnumber}_{clsize}.log"
    shell:
        '''
        {input.script} run{wildcards.runnumber}  {wildcards.clsize} \
        > {log} 2>&1
        '''

        #Escan; Iscan; boxscan; linescan

rule maketestfile: 
    input:
        "rootfile/run20_4_sum1d.root",
        "rootfile/run21_4_sum1d.root",
        "rootfile/run22_4_sum1d.root",
        "rootfile/run24_4_sum1d.root",
        "rootfile/run31_4_sum1d.root",
        "rootfile/run34_4_sum1d.root",

